### ISSUE TITLE
Проверка лабораторной работы 5

### ISSUE THREAD

**Issue by DX37** [DX37/Lab5#1]
Работу выполнил:
* Курносенко Максим Сергеевич

To: @evgeny-p

**Comment by evgeny-p** [comment]
1. Возврат результата из функции через глобальные переменные — худший из возможных вариантов. Наличие глобальных переменных порождает неявные зависимости: крайне затруднительно определить, какая часть кода действительно может менять значения переменных. Также в один момент времени в приложении может быть только один результат работы функции.

1. Для тест-кейсов нужны более осмысленные имена, чем `test[123]`. По такому отчету невозможно сказать, что именно тестировалось:

  ```
  TEST 1/3 func_suite:test3 [OK]
  TEST 2/3 func_suite:test2 [OK]
  TEST 3/3 func_suite:test1 [OK]
  RESULTS: 3 tests (3 ok, 0 failed, 0 skipped) ran in 0 ms
  ```

1. Тест-кейсы 1 и 2 образуют один класс эквивалентности: в обоих случаях дискриминант меньше нуля. Следовательно, можно оставить один из них.

1. Ошибка в тестовых данных: пересчитайте вручную корни уравнения на тестовых данных из третьего кейса.

1. Покрытие тестами неполное: как минимум, не хватает теста на случай с одним корнем. Также пользователь может ввести любые значения, в том числе все нули. Функция также должна быть способна обработать такую ситуцаию.

1. Съехало форматирование в третьем тест-кейсе.

1. В мейкфайле присутствуют правила только для сборки тестов. Должны быть также правила для сборки приложения и запуска тестов. Исправлено в рамках работы 6.

Все исправления предлагаю делать в репозитории с настроенным CI. Начало работы, как обычно, в отдельной ветке.
